"""Piano dei Conti — lookup tables LkpContoSP e LkpContoCE

Revision ID: mdm_11_lkp_conti
Revises: mdm_10_scad_trib
Create Date: 2026-02-02
"""
from alembic import op
import sqlalchemy as sa

revision = "mdm_11_lkp_conti"
down_revision = "mdm_10_scad_trib"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# Seed data extracted from app/services/xbrl_mapping.py
# Each tuple: (code, description, category)
# ---------------------------------------------------------------------------

SP_SEED = [
    ("ALTRE_RISERVE", "Altre riserve", "CAPITALE"),
    ("AZIONI_PROPRIE", "Azioni proprie", "CAPITALE"),
    ("AZIONI_RIMBORSABILI", "Azioni rimborsabili", "CAPITALE"),
    ("CAPITALE", "Capitale", "CAPITALE"),
    ("CAPITALE_SOCIALE", "Capitale sociale", "CAPITALE"),
    ("INTERESSI_DI_MINORANZA", "Interessi di minoranza", "CAPITALE"),
    ("PN_DI_PERTINENZA", "PN di pertinenza", "CAPITALE"),
    ("PATRIMONIO_NETTO", "Patrimonio netto", "CAPITALE"),
    ("RISERVA_LEGALE", "Riserva legale", "CAPITALE"),
    ("RISERVA_RIVALUTAZIONE", "Riserva rivalutazione", "CAPITALE"),
    ("RISERVA_SOVRAPPREZZO", "Riserva sovrapprezzo", "CAPITALE"),
    ("RISERVE_DI_VALUTAZIONE", "Riserve di valutazione", "CAPITALE"),
    ("SOVRAPPREZZO_AZIONI", "Sovrapprezzo azioni", "CAPITALE"),
    ("STRUMENTI_DI_CAPITALE", "Strumenti di capitale", "CAPITALE"),
    ("TOT_PATRIMONIO_NETTO", "Tot. patrimonio netto", "CAPITALE"),
    ("TOTALE_PATRIMONIO_NETTO", "Totale patrimonio netto", "CAPITALE"),
    ("ALTRE_ATTIVITA", "Altre attivita'", "CREDITI"),
    ("ALTRE_ATTIVITA_FINANZIARIE_CORRENTI", "Altre attivita' finanziarie correnti", "CREDITI"),
    ("ALTRI_CREDITI_CORRENTI", "Altri crediti correnti", "CREDITI"),
    ("ATT_FIN_FVTPL", "Att. fin. FVTPL", "CREDITI"),
    ("ATT_FIN_DESIGNATE_FVTPL", "Att. fin. designate FVTPL", "CREDITI"),
    ("ATT_FIN_OBBLIG_FVTPL", "Att. fin. obblig. FVTPL", "CREDITI"),
    ("ATT_FIN_TRADING", "Att. fin. trading", "CREDITI"),
    ("ATT_FINANZIARIE_A_COSTO_AMMORT", "Att. finanziarie a costo ammort.", "CREDITI"),
    ("ATT_NON_CORRENTI_IN_DISMISSIONE", "Att. non correnti in dismissione", "CREDITI"),
    ("ATTIVITA_ASSICURATIVE", "Attivita' assicurative", "CREDITI"),
    ("ATTIVITA_FIN_NON_IMMOB", "Attivita' fin. non immob.", "CREDITI"),
    ("ATTIVITA_FISCALI", "Attivita' fiscali", "CREDITI"),
    ("CONTRATTI_ASSICURATIVI_ATTIVO", "Contratti assicurativi (attivo)", "CREDITI"),
    ("CONTRATTI_RIASS_ATTIVO", "Contratti riass. (attivo)", "CREDITI"),
    ("CREDITI_COMMERCIALI", "Crediti commerciali", "CREDITI"),
    ("CREDITI_COMMERCIALI_CORRENTI", "Crediti commerciali correnti", "CREDITI"),
    ("CREDITI_TRIBUTARI", "Crediti tributari", "CREDITI"),
    ("CREDITI_TRIBUTARI_CORRENTI", "Crediti tributari correnti", "CREDITI"),
    ("CREDITI_VERSO_ALTRI", "Crediti verso altri", "CREDITI"),
    ("CREDITI_VERSO_SOCI", "Crediti verso soci", "CREDITI"),
    ("CREDITI_VS_BANCHE", "Crediti vs banche", "CREDITI"),
    ("CREDITI_VS_CLIENTELA", "Crediti vs clientela", "CREDITI"),
    ("CREDITI_VS_CLIENTI", "Crediti vs clienti", "CREDITI"),
    ("CREDITI_VS_SOCI_PER_VERS_DOVUTI", "Crediti vs soci per vers. dovuti", "CREDITI"),
    ("DERIVATI_ATTIVI_DI_COPERTURA", "Derivati attivi di copertura", "CREDITI"),
    ("IMPOSTE_ANTICIPATE", "Imposte anticipate", "CREDITI"),
    ("RATEI_E_RISCONTI_ATTIVI", "Ratei e risconti attivi", "CREDITI"),
    ("RISCONTI_ATTIVI", "Risconti attivi", "CREDITI"),
    ("TOT_ATTIVO", "Tot. attivo", "CREDITI"),
    ("TOT_ATTIVO_CIRCOLANTE", "Tot. attivo circolante", "CREDITI"),
    ("TOT_CREDITI", "Tot. crediti", "CREDITI"),
    ("TOTALE_ATTIVO", "Totale attivo", "CREDITI"),
    ("TOTALE_ATTIVO_CORRENTE", "Totale attivo corrente", "CREDITI"),
    ("ALTRE_PASSIVITA", "Altre passivita'", "DEBITI"),
    ("ALTRI_DEBITI", "Altri debiti", "DEBITI"),
    ("ALTRI_DEBITI_CORRENTI", "Altri debiti correnti", "DEBITI"),
    ("CONTRATTI_ASSICURATIVI_PASSIVO", "Contratti assicurativi (passivo)", "DEBITI"),
    ("CONTRATTI_RIASS_PASSIVO", "Contratti riass. (passivo)", "DEBITI"),
    ("DEBITI", "Debiti", "DEBITI"),
    ("DEBITI_COMMERCIALI", "Debiti commerciali", "DEBITI"),
    ("DEBITI_COMMERCIALI_CORRENTI", "Debiti commerciali correnti", "DEBITI"),
    ("DEBITI_LEASING_CORRENTI", "Debiti leasing correnti", "DEBITI"),
    ("DEBITI_LEASING_NON_CORRENTI", "Debiti leasing non correnti", "DEBITI"),
    ("DEBITI_LUNGO_TERMINE", "Debiti lungo termine", "DEBITI"),
    ("DEBITI_PREVIDENZIALI", "Debiti previdenziali", "DEBITI"),
    ("DEBITI_TRIBUTARI", "Debiti tributari", "DEBITI"),
    ("DEBITI_TRIBUTARI_CORRENTI", "Debiti tributari correnti", "DEBITI"),
    ("DEBITI_VS_BANCHE", "Debiti vs banche", "DEBITI"),
    ("DEBITI_VS_BANCHE_DEPOSITI", "Debiti vs banche (depositi)", "DEBITI"),
    ("DEBITI_VS_BANCHE_BREVE", "Debiti vs banche breve", "DEBITI"),
    ("DEBITI_VS_CLIENTELA_DEPOSITI", "Debiti vs clientela (depositi)", "DEBITI"),
    ("DEBITI_VS_FORNITORI", "Debiti vs fornitori", "DEBITI"),
    ("DERIVATI_PASSIVI_DI_COPERTURA", "Derivati passivi di copertura", "DEBITI"),
    ("FINANZIAMENTI_CORRENTI", "Finanziamenti correnti", "DEBITI"),
    ("FINANZIAMENTI_NON_CORRENTI", "Finanziamenti non correnti", "DEBITI"),
    ("PASS_FIN_DESIGNATE_FVTPL", "Pass. fin. designate FVTPL", "DEBITI"),
    ("PASS_FIN_TRADING", "Pass. fin. trading", "DEBITI"),
    ("PASS_FINANZIARIE_COSTO_AMMORT", "Pass. finanziarie costo ammort.", "DEBITI"),
    ("PASS_IN_DISMISSIONE", "Pass. in dismissione", "DEBITI"),
    ("PASSIVITA_ASSICURATIVE", "Passivita' assicurative", "DEBITI"),
    ("PASSIVITA_FISCALI", "Passivita' fiscali", "DEBITI"),
    ("RATEI_E_RISCONTI_PASSIVI", "Ratei e risconti passivi", "DEBITI"),
    ("TOT_DEBITI", "Tot. debiti", "DEBITI"),
    ("TOT_PASSIVO", "Tot. passivo", "DEBITI"),
    ("TOTALE_PASSIVO", "Totale passivo", "DEBITI"),
    ("TOTALE_PASSIVO_CORRENTE", "Totale passivo corrente", "DEBITI"),
    ("TOTALE_PASSIVO_E_PN", "Totale passivo e PN", "DEBITI"),
    ("TOTALE_PASSIVO_NON_CORRENTE", "Totale passivo non corrente", "DEBITI"),
    ("ALTRI_FONDI_RISCHI_E_ONERI", "Altri fondi rischi e oneri", "FONDI"),
    ("FONDI_GARANZIE_E_IMPEGNI", "Fondi garanzie e impegni", "FONDI"),
    ("FONDI_NON_CORRENTI", "Fondi non correnti", "FONDI"),
    ("FONDI_PENSIONE", "Fondi pensione", "FONDI"),
    ("FONDI_RISCHI_E_ONERI", "Fondi rischi e oneri", "FONDI"),
    ("IMPOSTE_DIFFERITE", "Imposte differite", "FONDI"),
    ("TFR", "TFR", "FONDI"),
    ("TFR_E_FONDI_PERSONALE", "TFR e fondi personale", "FONDI"),
    ("ATT_FIN_FVOCI", "Att. fin. FVOCI", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("ATTIVITA_FINANZIARIE_NON_CORRENTI", "Attivita' finanziarie non correnti", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("IMMOB_FINANZIARIE", "Immob. finanziarie", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("PARTECIPAZIONI", "Partecipazioni", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("PARTECIPAZIONI_COLLEGATE", "Partecipazioni collegate", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("PARTECIPAZIONI_CONTROLLATE", "Partecipazioni controllate", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("PARTECIPAZIONI_EQUITY_METHOD", "Partecipazioni equity method", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("TITOLI_DI_DEBITO", "Titoli di debito", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("TOT_IMMOB_FINANZIARIE", "Tot. immob. finanziarie", "IMMOBILIZZAZIONI_FINANZIARIE"),
    ("AVVIAMENTO", "Avviamento", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("COSTI_DI_IMPIANTO", "Costi di impianto", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("COSTI_DI_SVILUPPO", "Costi di sviluppo", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("DI_CUI_AVVIAMENTO", "di cui: avviamento", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("IMMOB_IMMATERIALI", "Immob. immateriali", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("IMMOB_IMMATERIALI_E_AVVIAMENTO", "Immob. immateriali e avviamento", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("IMMOB_IMMATERIALI_TOTALI", "Immob. immateriali totali", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("TOT_IMMOB_IMMATERIALI", "Tot. immob. immateriali", "IMMOBILIZZAZIONI_IMMATERIALI"),
    ("ATTIVITA_MATERIALI", "Attivita' materiali", "IMMOBILIZZAZIONI_MATERIALI"),
    ("DIRITTI_DUSO_IFRS_16", "Diritti d'uso (IFRS 16)", "IMMOBILIZZAZIONI_MATERIALI"),
    ("FABBRICATI", "Fabbricati", "IMMOBILIZZAZIONI_MATERIALI"),
    ("IMMOB_MATERIALI", "Immob. materiali", "IMMOBILIZZAZIONI_MATERIALI"),
    ("IMPIANTI_E_MACCHINARI", "Impianti e macchinari", "IMMOBILIZZAZIONI_MATERIALI"),
    ("INVESTIMENTI_IMMOBILIARI", "Investimenti immobiliari", "IMMOBILIZZAZIONI_MATERIALI"),
    ("MACCHINARI", "Macchinari", "IMMOBILIZZAZIONI_MATERIALI"),
    ("TERRENI", "Terreni", "IMMOBILIZZAZIONI_MATERIALI"),
    ("TOT_IMMOB_MATERIALI", "Tot. immob. materiali", "IMMOBILIZZAZIONI_MATERIALI"),
    ("TOT_IMMOBILIZZAZIONI", "Tot. immobilizzazioni", "IMMOBILIZZAZIONI_MATERIALI"),
    ("TOTALE_ATTIVO_NON_CORRENTE", "Totale attivo non corrente", "IMMOBILIZZAZIONI_MATERIALI"),
    ("CASSA", "Cassa", "LIQUIDITA_E_ESIGIBILITA_IMMEDIATE"),
    ("DENARO_IN_CASSA", "Denaro in cassa", "LIQUIDITA_E_ESIGIBILITA_IMMEDIATE"),
    ("DEPOSITI_BANCARI", "Depositi bancari", "LIQUIDITA_E_ESIGIBILITA_IMMEDIATE"),
    ("DISPONIBILITA_LIQUIDE", "Disponibilita' liquide", "LIQUIDITA_E_ESIGIBILITA_IMMEDIATE"),
    ("MATERIE_PRIME", "Materie prime", "RIMANENZE"),
    ("PRODOTTI_FINITI", "Prodotti finiti", "RIMANENZE"),
    ("RIMANENZE", "Rimanenze", "RIMANENZE"),
    ("TOT_RIMANENZE", "Tot. rimanenze", "RIMANENZE"),
    ("UTILI_A_NUOVO", "Utili a nuovo", "UTILE_PERDITA_A_NUOVO"),
    ("UTILI_PERDITE_A_NUOVO", "Utili/perdite a nuovo", "UTILE_PERDITA_A_NUOVO"),
    ("ACCONTO_DIVIDENDI", "Acconto dividendi", "UTILE_PERDITA_ESERCIZIO"),
    ("UTILE_DI_PERTINENZA", "Utile di pertinenza", "UTILE_PERDITA_ESERCIZIO"),
    ("UTILE_DI_TERZI", "Utile di terzi", "UTILE_PERDITA_ESERCIZIO"),
    ("UTILE_PERDITA_ESERCIZIO", "Utile/perdita esercizio", "UTILE_PERDITA_ESERCIZIO"),
]

CE_SEED = [
    ("AMMORT_E_RETTIFICHE_ATT_IMMATERIALI", "Ammort. e rettifiche att. immateriali", "AMMORTAMENTI_IMMATERIALI"),
    ("AMMORT_IMMOB_IMMATERIALI", "Ammort. immob. immateriali", "AMMORTAMENTI_IMMATERIALI"),
    ("AMMORTAMENTI_IMMATERIALI", "Ammortamenti immateriali", "AMMORTAMENTI_IMMATERIALI"),
    ("SVALUTAZIONE_AVVIAMENTO", "Svalutazione avviamento", "AMMORTAMENTI_IMMATERIALI"),
    ("AMMORT_E_RETTIFICHE_ATT_MATERIALI", "Ammort. e rettifiche att. materiali", "AMMORTAMENTI_MATERIALI"),
    ("AMMORT_E_SVALUTAZIONI", "Ammort. e svalutazioni", "AMMORTAMENTI_MATERIALI"),
    ("AMMORT_IMMOB_MATERIALI", "Ammort. immob. materiali", "AMMORTAMENTI_MATERIALI"),
    ("AMMORTAMENTI", "Ammortamenti", "AMMORTAMENTI_MATERIALI"),
    ("AMMORTAMENTI_MATERIALI", "Ammortamenti materiali", "AMMORTAMENTI_MATERIALI"),
    ("RETTIFICHE_IFRS9_COSTO_AMMORT", "Rettifiche IFRS9 costo ammort.", "AMMORTAMENTI_MATERIALI"),
    ("RETTIFICHE_IFRS9_FVOCI", "Rettifiche IFRS9 FVOCI", "AMMORTAMENTI_MATERIALI"),
    ("RETTIFICHE_SU_ATT_MATERIALI_E_IMMAT", "Rettifiche su att. materiali e immat.", "AMMORTAMENTI_MATERIALI"),
    ("RETTIFICHE_RIPRESE_IFRS_9", "Rettifiche/riprese IFRS 9", "AMMORTAMENTI_MATERIALI"),
    ("RETTIFICHE_RIPRESE_PER_RISCHIO_CREDITO", "Rettifiche/riprese per rischio credito", "AMMORTAMENTI_MATERIALI"),
    ("SVALUTAZIONI", "Svalutazioni", "AMMORTAMENTI_MATERIALI"),
    ("CONTRIBUTI_SOCIALI", "Contributi sociali", "COSTI_PERSONALE"),
    ("COSTI_DEL_PERSONALE", "Costi del personale", "COSTI_PERSONALE"),
    ("COSTO_DEL_PERSONALE", "Costo del personale", "COSTI_PERSONALE"),
    ("ONERI_SOCIALI", "Oneri sociali", "COSTI_PERSONALE"),
    ("SALARI_E_STIPENDI", "Salari e stipendi", "COSTI_PERSONALE"),
    ("SPESE_PER_IL_PERSONALE", "Spese per il personale", "COSTI_PERSONALE"),
    ("ACCANTONAMENTI_GARANZIE", "Accantonamenti garanzie", "FONDI"),
    ("ACCANTONAMENTI_NETTI_FONDI_RISCHI", "Accantonamenti netti fondi rischi", "FONDI"),
    ("ALTRI_ACCANTONAMENTI_NETTI", "Altri accantonamenti netti", "FONDI"),
    ("IMPOSTE_CORRENTI", "Imposte correnti", "IMPOSTE"),
    ("IMPOSTE_DIFFERITE_CE", "Imposte differite", "IMPOSTE"),
    ("IMPOSTE_E_TASSE_NON_PAGATE", "Imposte e tasse non pagate", "IMPOSTE"),
    ("IMPOSTE_REDDITO_ESERCIZIO", "Imposte reddito esercizio", "IMPOSTE"),
    ("IMPOSTE_SUL_REDDITO", "Imposte sul reddito", "IMPOSTE"),
    ("COSTI_MAT_PRIME_E_MERCI", "Costi mat. prime e merci", "MATERIE_PRIME_E_MERCI"),
    ("COSTI_MATERIE_PRIME", "Costi materie prime", "MATERIE_PRIME_E_MERCI"),
    ("COSTO_MERCI_VENDUTE", "Costo merci vendute", "MATERIE_PRIME_E_MERCI"),
    ("MATERIE_PRIME_CONSUMATE", "Materie prime consumate", "MATERIE_PRIME_E_MERCI"),
    ("SVALUTAZIONE_RIMANENZE", "Svalutazione rimanenze", "MATERIE_PRIME_E_MERCI"),
    ("VAR_RIMANENZE_PROD_FINITI", "Var. rimanenze prod. finiti", "MATERIE_PRIME_E_MERCI"),
    ("VARIAZIONE_RIMANENZE", "Variazione rimanenze", "MATERIE_PRIME_E_MERCI"),
    ("INTERESSI_E_ONERI_FINANZIARI", "Interessi e oneri finanziari", "ONERI_FINANZIARI"),
    ("INTERESSI_PASSIVI", "Interessi passivi", "ONERI_FINANZIARI"),
    ("INTERESSI_PASSIVI_E_ONERI_SIM", "Interessi passivi e oneri sim.", "ONERI_FINANZIARI"),
    ("INTERESSI_SU_FINANZIAMENTI", "Interessi su finanziamenti", "ONERI_FINANZIARI"),
    ("ONERI_FINANZIARI", "Oneri finanziari", "ONERI_FINANZIARI"),
    ("ALTRI_PROVENTI_FINANZIARI", "Altri proventi finanziari", "PROVENTI_FINANZIARI"),
    ("DIVIDENDI_PERCEPITI", "Dividendi percepiti", "PROVENTI_FINANZIARI"),
    ("INTERESSI_ATTIVI_CE", "Interessi attivi", "PROVENTI_FINANZIARI"),
    ("PROVENTI_FINANZIARI", "Proventi finanziari", "PROVENTI_FINANZIARI"),
    ("PROVENTI_ONERI_FINANZIARI", "Proventi/oneri finanziari", "PROVENTI_FINANZIARI"),
    ("QUOTA_UTILI_PARTECIPATE", "Quota utili partecipate", "PROVENTI_FINANZIARI"),
    ("RETTIFICHE_ATT_FINANZIARIE", "Rettifiche att. finanziarie", "PROVENTI_FINANZIARI"),
    ("RISULTATO_ALTRE_ATT_FVTPL", "Risultato altre att. FVTPL", "PROVENTI_FINANZIARI"),
    ("RISULTATO_ATT_DESIGNATE_FVTPL", "Risultato att. designate FVTPL", "PROVENTI_FINANZIARI"),
    ("RISULTATO_ATT_FIN_TRADING_FVTPL", "Risultato att. fin. trading/FVTPL", "PROVENTI_FINANZIARI"),
    ("RISULTATO_ATT_MAT_IMMAT_A_FV", "Risultato att. mat./immat. a FV", "PROVENTI_FINANZIARI"),
    ("RISULTATO_ATT_OBBLIG_FVTPL", "Risultato att. obblig. FVTPL", "PROVENTI_FINANZIARI"),
    ("RISULTATO_COPERTURE", "Risultato coperture", "PROVENTI_FINANZIARI"),
    ("RISULTATO_FIN_ASSICURATIVO", "Risultato fin. assicurativo", "PROVENTI_FINANZIARI"),
    ("RISULTATO_FIN_RIASSICURATIVO", "Risultato fin. riassicurativo", "PROVENTI_FINANZIARI"),
    ("RISULTATO_NETTO_COPERTURE", "Risultato netto coperture", "PROVENTI_FINANZIARI"),
    ("SALDO_PROVENTI_ONERI_FIN_ASSICUR", "Saldo proventi/oneri fin. assicur.", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_CESSIONE_ATT_PASS_FIN", "Utili/perdite cessione att./pass. fin.", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_CESSIONE_COSTO_AMMORT", "Utili/perdite cessione costo ammort.", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_CESSIONE_FVOCI", "Utili/perdite cessione FVOCI", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_CESSIONE_INVESTIMENTI", "Utili/perdite cessione investimenti", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_MODIF_CONTRATTUALI", "Utili/perdite modif. contrattuali", "PROVENTI_FINANZIARI"),
    ("UTILI_PERDITE_RIACQUISTO_PASSIVITA", "Utili/perdite riacquisto passivita'", "PROVENTI_FINANZIARI"),
    ("ALTRI_PROVENTI_ONERI_DI_GESTIONE", "Altri proventi/oneri di gestione", "RICAVI"),
    ("ALTRI_RICAVI", "Altri ricavi", "RICAVI"),
    ("ALTRI_RICAVI_E_PROVENTI", "Altri ricavi e proventi", "RICAVI"),
    ("COMMISSIONI_ATTIVE", "Commissioni attive", "RICAVI"),
    ("COMMISSIONI_NETTE", "Commissioni nette", "RICAVI"),
    ("DIFF_VALORE_COSTI_PRODUZIONE", "Diff. valore/costi produzione", "RICAVI"),
    ("INTERESSI_ATTIVI_EFF_INTEREST", "Interessi attivi (eff. interest)", "RICAVI"),
    ("INTERESSI_ATTIVI_E_PROVENTI_SIM", "Interessi attivi e proventi sim.", "RICAVI"),
    ("MARGINE_DINTERESSE", "Margine d'interesse", "RICAVI"),
    ("MARGINE_DI_INTERMEDIAZIONE", "Margine di intermediazione", "RICAVI"),
    ("PROVENTI_ONERI_STRAORDINARI", "Proventi/oneri straordinari", "RICAVI"),
    ("PROVENTI_RIASSICURAZIONE", "Proventi riassicurazione", "RICAVI"),
    ("RETTIFICHE_ATT_DISMESSE", "Rettifiche att. dismesse", "RICAVI"),
    ("RICAVI", "Ricavi", "RICAVI"),
    ("RICAVI_ASSICURATIVI", "Ricavi assicurativi", "RICAVI"),
    ("RICAVI_COSTI_NETTI_CONTRATTI_ASSICUR", "Ricavi/costi netti contratti assicur.", "RICAVI"),
    ("RICAVI_DA_CONTRATTI", "Ricavi da contratti", "RICAVI"),
    ("RICAVI_DELLE_VENDITE", "Ricavi delle vendite", "RICAVI"),
    ("RICAVI_VENDITE_E_PRESTAZIONI", "Ricavi vendite e prestazioni", "RICAVI"),
    ("RISULTATO_ANTE_IMPOSTE", "Risultato ante imposte", "RICAVI"),
    ("RISULTATO_ATT_DISMESSE", "Risultato att. dismesse", "RICAVI"),
    ("RISULTATO_ATT_FIN_E_ASSICUR", "Risultato att. fin. e assicur.", "RICAVI"),
    ("RISULTATO_ATT_IN_FUNZIONAMENTO", "Risultato att. in funzionamento", "RICAVI"),
    ("RISULTATO_COMPLESSIVO", "Risultato complessivo", "RICAVI"),
    ("RISULTATO_COMPLESSIVO_DI_PERTINENZA", "Risultato complessivo di pertinenza", "RICAVI"),
    ("RISULTATO_COMPLESSIVO_DI_TERZI", "Risultato complessivo di terzi", "RICAVI"),
    ("RISULTATO_NEGOZIAZIONE", "Risultato negoziazione", "RICAVI"),
    ("RISULTATO_NETTO_ATT_FINANZIARIE", "Risultato netto att. finanziarie", "RICAVI"),
    ("RISULTATO_OPERATIVO", "Risultato operativo", "RICAVI"),
    ("RISULTATO_SERVIZIO_ASSICURATIVO", "Risultato servizio assicurativo", "RICAVI"),
    ("TOT_VALORE_PRODUZIONE", "Tot. valore produzione", "RICAVI"),
    ("UTILE_PER_AZIONE_BASE", "Utile per azione base", "RICAVI"),
    ("UTILE_PER_AZIONE_DILUITO", "Utile per azione diluito", "RICAVI"),
    ("UTILE_PERDITA_ESERCIZIO_CE", "Utile/perdita esercizio", "RICAVI"),
    ("VALORE_DELLA_PRODUZIONE", "Valore della produzione", "RICAVI"),
    ("ACCANTONAMENTI_E_ALTRI_ONERI_PROVENTI", "Accantonamenti e altri oneri/proventi", "SERVIZI"),
    ("ALTRE_SPESE_AMMINISTRATIVE", "Altre spese amministrative", "SERVIZI"),
    ("ALTRE_SPESE_OPERATIVE", "Altre spese operative", "SERVIZI"),
    ("COMMISSIONI_PASSIVE", "Commissioni passive", "SERVIZI"),
    ("COSTI_DELLA_PRODUZIONE", "Costi della produzione", "SERVIZI"),
    ("COSTI_DISTRIBUZIONE", "Costi distribuzione", "SERVIZI"),
    ("COSTI_OPERATIVI", "Costi operativi", "SERVIZI"),
    ("COSTI_PER_SERVIZI", "Costi per servizi", "SERVIZI"),
    ("COSTI_RIASSICURAZIONE", "Costi riassicurazione", "SERVIZI"),
    ("COSTI_SERVIZIO_ASSICURATIVO", "Costi servizio assicurativo", "SERVIZI"),
    ("GODIMENTO_BENI_TERZI", "Godimento beni terzi", "SERVIZI"),
    ("ONERI_DIVERSI_DI_GESTIONE", "Oneri diversi di gestione", "SERVIZI"),
    ("SERVIZI_E_ALTRI_COSTI", "Servizi e altri costi", "SERVIZI"),
    ("SPESE_AMMINISTRATIVE", "Spese amministrative", "SERVIZI"),
    ("SPESE_COMMERCIALI", "Spese commerciali", "SERVIZI"),
    ("TOT_COSTI_PRODUZIONE", "Tot. costi produzione", "SERVIZI"),
]


def upgrade():
    # Create SP lookup table
    lkp_sp = op.create_table(
        "lkp_conti_sp",
        sa.Column("code", sa.String(256), primary_key=True),
        sa.Column("description", sa.String(512), nullable=False),
        sa.Column("category", sa.String(128), nullable=False, index=True),
    )
    # Seed SP accounts
    op.bulk_insert(lkp_sp, [
        {"code": code, "description": desc, "category": cat}
        for code, desc, cat in SP_SEED
    ])

    # Create CE lookup table
    lkp_ce = op.create_table(
        "lkp_conti_ce",
        sa.Column("code", sa.String(256), primary_key=True),
        sa.Column("description", sa.String(512), nullable=False),
        sa.Column("category", sa.String(128), nullable=False, index=True),
    )
    # Seed CE accounts
    op.bulk_insert(lkp_ce, [
        {"code": code, "description": desc, "category": cat}
        for code, desc, cat in CE_SEED
    ])


def downgrade():
    op.drop_table("lkp_conti_ce")
    op.drop_table("lkp_conti_sp")
