INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '501000', 'PRODOTTI FINITI C/VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '502000', 'MERCI C/VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '503000', 'CORRISPETTIVI', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '504000', 'RESI SU VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '505000', 'SCONTI SU VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '506000', 'ABBUONI SU VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '507000', 'PREMI SU VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '508000', 'ALTRI RICAVI DELLE VENDITE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '509000', 'RICAVI PER PRESTAZ. DI SERVIZI', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '510000', 'CORRISPET. PER PRESTAZ. DI SERV.', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '511000', 'ALTRI RICAVI DELLE PRESTAZIONI', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '512000', 'RICAVI DA SAL', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '550000', 'PRODOTTI IN CORSO DI LAVORAZIONE C/ESISTENZE INIZIALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '551000', 'PRODOTTI IN CORSO DI LAVORAZIONE C/RIMANENZE FINALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '552000', 'SEMILAVORATI C/ESISTENZE INIZIALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '553000', 'SEMILAVORATI C/RIMANENZE FINALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '554000', 'PRODOTTI FINITI C/ESISTENZE INIZIALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '555000', 'PRODOTTI FINITI C/RIMANENZE FINALI', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '556000', 'LAVORI IN CORSO SU ORDINAZIONE  Rim IN', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '557000', 'LAVORI IN CORSO SU ORDINAZIONE  Rim Fin', 'CE_RIMANENZE_PF', 'RIMANENZE PF');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '558000', 'MATERIE PRIME C/ESIST.INIZIALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '559000', 'MATERIE PRIME C/RIMANENZE FINALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '560000', 'MATERIE SUSS. C/ESIST.INIZIALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '561000', 'MATERIE SUSS. C/RIMAN. FINALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '562000', 'MATERIE DI CONS.C/ESIST.INIZIALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '563000', 'MATERIE DI CONSUMO C/RIM.FINALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '564000', 'MATERIALI VARI C/ESIST.INIZIALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '565000', 'MATERIALI VARI C/RIM. FINALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '566000', 'MATERIALI C/ESIST.INIZ.NON RILEV', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '567000', 'MATERIALI C/RIM.FINAL.NON RILEV.', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '568000', 'MERCI C/ESISTENZE INIZIALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '569000', 'MERCI C/RIM. FINALI', 'CE_RIMANENZE_MP', 'RIMANENZE MP');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '570000', 'CAPITALIZZAZIONE DI COSTI DI IMMOBILIZZAZIONI IMMATERIALI', 'CE_CAPITALIZZAZIONE_COSTI', 'CAPITALIZZAZIONE COSTI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '571000', 'COSTRUZIONI INTERNE DI IMMOBILIZZAZIONI MATERIALI', 'CE_CAPITALIZZAZIONE_COSTI', 'CAPITALIZZAZIONE COSTI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '601000', 'MATERIE PRIME C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '602000', 'MATERIE SUSS. C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '603000', 'SEMILAVORATI C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '604000', 'MATERIE DI CONSUMO C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '605000', 'MERCI C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '606000', 'IMBALLAGGI C/ACQUISTI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '650000', 'TRASPORTI SU ACQUISTI E VENDITE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '651000', 'DAZI E ONERI SU ACQUISTI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '652000', 'LAVOR.DI TERZI P/PROD.DI BENI E SERVIZI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '653000', 'ABBUONI E SCONTI PASSIVI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '654000', 'ENERGIA ELETTRICA FORZA MOTRICE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '655000', 'ENERGIA ELETTRICA ALTRI UTILIZZI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '656000', 'UTENZE GAS', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '657000', 'UTENZE CARBURANTI E LUBRIFICANTI NON PER TRAZIONE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '658000', 'ALTRE UTENZE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '659000', 'CANONI DI MANUTENZIONE PERIODICA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '660000', 'MANUTENZIONE BENI PROPRI MOBILI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '661000', 'MANUTENZIONE BENI PROPRI IMMOBILI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '662000', 'MANUTENZIONE BENI TERZI MOBILI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '663000', 'MANUTENZIONE BENI TERZI IMMOBILI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '664000', 'CONAI E COSTI DI SMALTIMENTO', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '664010', 'ALTRE MANUTENZIONI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '665000', 'ASSICURAZIONI NON OBBLIGATORIE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '666000', 'ASSICURAZIONI OBBLIGATORIE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '667000', 'VIGILANZA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '668000', 'COSTI PER SERVIZI DI PULIZIA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '669000', 'COMPENSI AMMINISTRATORI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '670000', 'COMPENSI SINDACI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '671000', 'COMPENSI REVISORI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '672000', 'COMPENSI COLLAB.COORD.', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '673000', 'COMPENSI LAVORO OCCASIONALE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '674000', 'COSTI TRASFERTE E PEDAGGI AUTOSTRADALI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '675000', 'COMPENSI PROFESSIONALI (ALTRI)', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '676000', 'PROVVIGIONI A INTERMEDIARI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '677000', 'PUBBLICITA'' E FIERE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '678000', 'CONSULENZE FISCALI E CONTABILI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '679000', 'CONSULENZE LEGALI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '680000', 'UTENZE TELEFONICHE E CELLULARI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '681000', 'SPESE DI RAPPRESENTANZA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '682000', 'PASTI, SOGGIORNI E VIAGGI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '683000', 'CARBURANTI PER AUTOMEZZI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '684000', 'ALTRE CONSULENZA TECNICHE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '685000', 'ONERI BANCARI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '686000', 'ONERI DI FACTORING', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '687000', 'CANONE INTERNET E SOFTWARE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '688000', 'CANONE ASSISTENZA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '689000', 'ALTRI ACQUISTI DI MERCI E SIMILI', 'CE_MATERIE_PRIME_E_MERCI', 'MATERIE PRIME E MERCI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '690000', 'FITTI ATTIVI', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '691000', 'CONSULENZE AMM.VE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '692000', 'CONSULENZE TECNICHE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '693000', 'PLUSVALENZE ORDINARIE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '694000', 'CANCELLERIA', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '695000', 'MATERIALE PUBBLICITARIO', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '696000', 'ALTRI COSTI PER SERVIZI', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '697000', 'CARBURANTI E LUBRIFICANTI AUTOVETTURE', 'CE_SERVIZI', 'SERVIZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '698000', 'CONTRIBUTI IN CONTO ESERCIZIO', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '700000', 'SPESE CONDOMINIALI E FACILITY', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '701000', 'FITTI PASSIVI (BENI IMMOBILI)', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '702000', 'CANONI AFFITTO D''AZIENDA', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '703000', 'NOLEGGIO ATTREZZATURE', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '704000', 'NOLEGGIO IMPIANTI', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '705000', 'NOLEGGIO AUTO', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '706000', 'ALTRI NOLEGGI', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '707000', 'LOCAZIONI PASSIVI (ALTRE)', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '708000', 'ONERI DIVERSI DI GESTIONE', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '709000', 'MINUSVALENZE ORDINARIE', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '710000', 'CANONI DI LEASING', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '711000', 'ALTRI COST.PER GOD.BENI DI TERZI', 'CE_GODIMENTO_BENI_TERZI', 'GODIMENTO BENI TERZI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '750000', 'SALARI E STIPENDI', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '751000', 'STIP.AMM.SOCI', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '752000', 'ONERI SOCIALI INPS', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '753000', 'ONERI SOCIALI INAIL', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '754000', 'ALTRI ONERI SOCIALI', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '755000', 'TFR', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '756000', 'TRATTAMENTO DI QUIESC.E SIMILI', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '757000', 'INDUMENTI DI LAVORO', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '758000', 'ALTRI COSTI DEL PERSONALE', 'CE_COSTI_PERSONALE', 'COSTI PERSONALE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '770000', 'AMM.TO COSTI D''IMPIANTO', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '771000', 'AMM.TO COSTI DI AMPLIAMENTO', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '772000', 'AMM.TO COSTI RIC. SVIL. PUBBL.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '773000', 'AMM.TO COSTI DI SVILUPPO', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '774000', 'AMM.TO DIRITTI DI BREVETTO', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '775000', 'AMM.TO DIR.DI UTIL.DELLE OP.ING.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '776000', 'AMM.TO LIC.USO SOFT.A TEMP.IND.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '777000', 'AMM.TO CONC.,LIC.E DIRITTI SIM.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '778000', 'AMM.TO MARCHI DI FABB.E DI COMM.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '779000', 'AMMORTAMENTO MARCHI INDEDUCIBILE', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '780000', 'AMM.TO LIC.USO SOFT.A TEMP.DET.', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '781000', 'AMM.TO AVVIAMENTO', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '782000', 'AMM.TO ALTRE IMM.IMMATERIALI', 'CE_AMMORTAMENTI_IMMATERIALI', 'AMMORTAMENTI IMMATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '790000', 'AMM.TO ORDINARIO TERRENI', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '791000', 'AMM.TO ORD.FABBRICATI', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '792000', 'AMM.TO IMPIANTI E MACCHINARIO', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '793000', 'AMM.TO ATTREZ. IND.LI E COMM.LI', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '794000', 'AMM.TO MOBILI E MACCHINE D''UFF.', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '795000', 'AMM.TO AUTOMEZZI (ALTRI BENI)', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '796000', 'AMM.TO ALTRI BENI MATERIALI', 'CE_AMMORTAMENTI_MATERIALI', 'AMMORTAMENTI MATERIALI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '800000', 'ACCANTONAMENTO PER RISCHI CREDITI', 'CE_ACCANTONAMENTI', 'ACCANTONAMENTI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '801000', 'ALTRI ACCANTONAMENTI', 'CE_ACCANTONAMENTI', 'ACCANTONAMENTI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '810000', 'IMPOSTE INDIRETTE TASSE E IMPOSTE', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '811000', 'ALTRI ONERI DIVERSI DI GESTIONE', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '820000', 'PROVENTI STRAORDINARI', 'CE_PROVENTI_STRAORDINARI', 'PROVENTI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '821000', 'RIVALUTAZIONI', 'CE_PROVENTI_STRAORDINARI', 'PROVENTI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '822000', 'PLUSVALENZE STRAORDINARIE', 'CE_PROVENTI_STRAORDINARI', 'PROVENTI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '823000', 'SOPRAVVENIENZE ORDINARIE', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '824000', 'ALTRI RICAVI E PROVENTI DIVERSI DALLE VENDITE E PRESTAZIONI', 'CE_PROVENTI_STRAORDINARI', 'PROVENTI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '825000', 'CONTRIBUTI IN CONTO IMPIANTI', 'CE_RICAVI', 'RICAVI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '830000', 'ONERI STRAORDINARI', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '831000', 'ALTRI ONERI STRAORDINARI', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '832000', 'MINUSVALENZE STRAORDINARIE', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '833000', 'SOPRAVVENIENZE PASSIVE', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '834000', 'PERDITE SU CREDITI', 'CE_ONERI_DIVERSI_DI_GESTIONE', 'ONERI DIVERSI DI GESTIONE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '835000', 'SVALUTAZIONE MAGAZZINO', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '836000', 'SVALUTAZIONE CREDITI FINANZIARI', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '837000', 'ALTRE SVALUTAZIONI', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '840000', 'PROVENTI DA PARTECIPAZIONI', 'CE_PROVENTI_FINANZIARI', 'PROVENTI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '841000', 'INTERESSI ATTIVI FINANZIARI', 'CE_PROVENTI_FINANZIARI', 'PROVENTI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '842000', 'UTILI SU CAMBI', 'CE_PROVENTI_FINANZIARI', 'PROVENTI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '843000', 'ALTRI PROVENTI FINANZIARI', 'CE_PROVENTI_FINANZIARI', 'PROVENTI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '850000', 'INTERESSI PASSIVI C/C Bancari', 'CE_ONERI_FINANZIARI', 'ONERI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '851000', 'INTERESSI PASSIVI Mutui e Finanziamenti', 'CE_ONERI_FINANZIARI', 'ONERI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '852000', 'PERDITE SU CAMBI', 'CE_ONERI_FINANZIARI', 'ONERI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '853000', 'MULTE, AMMENDE E SANZIONI', 'CE_ONERI_STRAORDINARI', 'ONERI STRAORDINARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '854000', 'ALTRI ONERI FINANZIARI', 'CE_ONERI_FINANZIARI', 'ONERI FINANZIARI');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '860000', 'ALTRE IMPOSTE (IRPEF)', 'CE_IMPOSTE', 'IMPOSTE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '861000', 'IRAP DELL''ESERCIZIO', 'CE_IMPOSTE', 'IMPOSTE');
INSERT INTO stg_map_ce (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '862000', 'IRES DELL''ESERCIZIO', 'CE_IMPOSTE', 'IMPOSTE');