INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10100', 'PARTECIPAZIONI IN IMPRESE CONTROLLATE', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10200', 'PARTECIPAZIONI IN IMPRESE COLLEGATE', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10300', 'PARTECIPAZIONI IN IMPRESE CONTROLLANTI', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10400', 'ALTRE PARTECIPAZIONI', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10500', 'IMMOBILIZZAZIONI IN CREDITI FINANZIARI', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10600', 'ALTRI TITOLI', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10700', 'AZIONI PROPRIE', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10800', 'STRUMENTI FINANZIARI DER.ATTIVI', 'SP_IMMOBILIZZAZIONI_FINANZIARIE', 'IMMOBILIZZAZIONI FINANZIARIE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '10900', 'ALTRE IMMOB.ZIONI IMMATERIALI', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11000', 'AVVIAMENTO', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11100', 'CONCESSIONI, LICENZE, MARCHI', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11200', 'COSTI RIC.,SVIL.,PUBBL. DA AMM.', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11300', 'DIRITTI DI BREV.E UTIL.OPERE ING', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11400', 'IMM.IMM. IN CORSO E ACCONTI', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11500', 'ALTRI BENI IMMATERIALI', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11600', 'ATTREZZATURE IND.LI E COMM.LI', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11700', 'AUTOMEZZI (ALTRI BENI)', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11800', 'COSTI DI IMPIANTO E AMPLIAMENTO', 'SP_IMMOBILIZZAZIONI_IMMATERIALI', 'IMMOBILIZZAZIONI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '11900', 'IMMOBIL. IN CORSO E ACCONTI', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '12000', 'IMPIANTI E MACCHINARIO', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '12100', 'MOBILI E MACC.D''UFF.(ALTRI BENI)', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '12200', 'TERRENI E FABBRICATI', 'SP_IMMOBILIZZAZIONI_MATERIALI', 'IMMOBILIZZAZIONI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20100', 'ACCONTI RIMANENZE', 'SP_RIMANENZE', 'RIMANENZE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20200', 'BENI IN LEASING', 'SP_IMMOBILIZZAZIONI_LEASING', 'IMMOBILIZZAZIONI LEASING');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20300', 'LAVORI IN CORSO SU ORDINAZIONE', 'SP_RIMANENZE', 'RIMANENZE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20400', 'MATERIE PRIME, SUSS.E DI CONSUMO', 'SP_RIMANENZE', 'RIMANENZE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20500', 'PROD.IN CORSO DI LAV. E SEMILAV.', 'SP_RIMANENZE', 'RIMANENZE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '20600', 'PRODOTTI FINITI E MERCI', 'SP_RIMANENZE', 'RIMANENZE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30100', 'ALTRI CREDITI TRIBUTARI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30200', 'ALTRI CREDITI TRIBUTARI oltre i 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30300', 'Attività Finanziaria ALTRE PARTECIPAZIONI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30400', 'Attività finanziaria STRUMENTI FINANZIARI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30500', 'Attività FinanziariALTRI TITOLI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30600', 'Attvità Finanziarie IN IMPRESE CONTR.', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30700', 'CREDITI PER IMPOSTE ANTICIPATE', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30800', 'CREDITI V/CLIENTI inferiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '30900', 'CREDITI V/CLIENTI superiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31000', 'CREDITI V/DIPENDENTI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31100', 'CREDITI V/FORNITORI (ACCONTI)', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31200', 'CREDITI V/IMPRESE Contr.te-Coll.te-Contr.ti inferiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31300', 'CREDITI V/IMPRESE Contr.te-Coll.te-Contr.ti superiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31400', 'CREDITI V/Istituti Previdenziali inferiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31500', 'CREDITI V/Istituti Previdenziali superiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31600', 'CREDITI V/SOCI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31700', 'CREDITI V/SOCI P/VERS.ANC.DOVUTI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31800', 'CREDITI DIVERSI', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '31900', 'CREDITO D''IMPOSTA', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32000', 'Credito Ires e Irap', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32100', 'Credito Iva', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32200', 'Fatture da Emettere', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32300', 'PARTECIPAZIONI V/IMPRESE Contr.te-Coll.te-Contr.ti inferiori ai 12 mesi', 'SP_CREDITI', 'CREDITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32400', 'RATEI ATTIVI', 'SP_RATEI_E_RISCONTI', 'RATEI E RISCONTI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32500', 'RISCONTI ATTIVI', 'SP_RATEI_E_RISCONTI', 'RATEI E RISCONTI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32600', 'ASSEGNI', 'SP_LIQUIDITA_E_ESIGIBILITA_IMMEDIATE', 'LIQUIDITA E ESIGIBILITA'' IMMEDIATE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32700', 'DENARO E VALORI IN CASSA', 'SP_LIQUIDITA_E_ESIGIBILITA_IMMEDIATE', 'LIQUIDITA E ESIGIBILITA'' IMMEDIATE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '32800', 'DEPOSITI BANCARI E POSTALI attivi', 'SP_LIQUIDITA_E_ESIGIBILITA_IMMEDIATE', 'LIQUIDITA E ESIGIBILITA'' IMMEDIATE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40000', 'ALTRI FONDI PER RISCHI ED ONERI', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40100', 'F.DI P/TRAT.QUIESC.E OBBL.SIMILI', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40200', 'F.DI RISCHI SU CREDITI V. CLIENT', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40300', 'F.DO SVALUT. IMMOB. IMMATERIALI', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40400', 'F.DO SVALUT. IMMOB. MATERIALI', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40500', 'F.DO SVALUTAZIONE MAGAZZINO', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40600', 'F/SVAL. IMM. FINANZIARIE', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40700', 'FONDO PER IMPOSTE', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '40800', 'TFR LAVORO SUBORDINATO', 'SP_FONDI', 'FONDI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50100', 'F/AMM ALTRE IMMOB. IMMATERIALI', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50200', 'F/AMM ATTREZ. IND.LI E COMM.LI', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50300', 'F/AMM AVVIAMENTO', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50400', 'F/AMM CONCESS. LICENZE MARCHI', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50500', 'F/AMM COSTI DI IMPIANTO E AMPL.', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50600', 'F/AMM COSTI DI RIC,SVIL,PUBB.AMM', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50700', 'F/AMM DIRITTI DI BREV. E UT. OP.', 'SP_F_DO_AMM_TO_IMM_NI_IMMATERIALI', 'F.DO AMM.TO IMM.NI IMMATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50800', 'F/AMM FABBRICATI', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '50900', 'F/AMM IMPIANTI E MACCHINARIO', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '51000', 'F/AMM. ALTRI BENI MATERIALI', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '51100', 'F/AMM. AUTOMEZZI (ALTRI BENI)', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '51200', 'F/AMM. MOBILI E MACCH. D''UFFICIO', 'SP_F_DO_AMM_TO_IMM_NI_MATERIALI', 'F.DO AMM.TO IMM.NI MATERIALI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60000', 'ALTRE RISERVE', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60100', 'CAPITALE', 'SP_CAPITALE', 'CAPITALE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60200', 'RISERVA DA SOPRAPREZ. AZ./QUOTE', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60300', 'RISERVA LEGALE', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60400', 'RISERVE DI RIVALUTAZIONE', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60500', 'Riserve di Utili non distribuiti', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60600', 'RISERVE STATUTARIE', 'SP_RISERVE', 'RISERVE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60700', 'UTILE (PERDITA) DELL''ESERCIZIO', 'SP_UTILE_PERDITA_ESERCIZIO', 'UTILE PERDITA ESERCIZIO');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60800', 'UTILI (PERDITE) PORTATI A NUOVO', 'SP_UTILE_PERDITA_A_NUOVO', 'UTILE PERDITA A NUOVO');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '60900', 'Crediti Versamenti Aumento Capitale', 'SP_CREDITI_X_AUMENTO_CAPITALE', 'CREDITI X AUMENTO CAPITALE');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70000', 'DEBITI V/BANCHE c/c passivi', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70100', 'ACCONTI DA CLIENTI E CAPARRE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70200', 'ALTRI DEBITI TRIBUTARI (OLTRE ESERCIZIO)', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70300', 'ALTRI DEBITI V/DIPENDENTI (OLTRE ESERCIZIO)', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70400', 'SINDACI E AMMINISTRATORI C/COMPENSI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70500', 'DEBITI DIVERSI E FATTURE DA RICEVERE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70600', 'DEBITI PREVIDENZIALI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70700', 'DEBITI PREVIDENZIALI RATEIZZATI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70800', 'DEBITI RAPP. DA TITOLI DI CRED.', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '70900', 'DEBITI TRIBUTARI RATEIZZATI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71000', 'DEBITI V/ALTRI FINANZIATORI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71100', 'DEBITI V/BANCHE Finanziamenti e Leasing', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71200', 'DEBITI V/DIPENDENTI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71300', 'DEBITI V/FINANZIAMENTO SOCI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71400', 'DEBITI V/FORNITORI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71500', 'DEBITI V/FORNITORI BENI STRUMENTALI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71600', 'DEBITI V/GRUPPO FINANZIARI BREVE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71700', 'DEBITI V/GRUPPO FINANZIARI MEDIO LUNGO', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71800', 'DEBITI V/IMPRESE GRUPPO COMM.LI BREVE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '71900', 'DEBITI V/IMPRESE GRUPPO MEDIO LUNGO', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72000', 'ERARIO C/IRES E IRAP BREVE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72100', 'ERARIO C/IVA', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72200', 'ERARIO C/RIT. LAVORO DIPENDENTE E COLLABORATORI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72300', 'NOTE CREDITO DA EMETTERE', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72400', 'OBBLIGAZIONI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72500', 'RATEI PASSIVI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72600', 'RISCONTI PASSIVI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72700', 'ALTRI DEBITI', 'SP_DEBITI', 'DEBITI');
INSERT INTO stg_map_sp (case_id, imported_code, imported_desc, riclass_code, riclass_desc) VALUES (NULL, '72800', 'SOCI C/UTILI', 'SP_DEBITI', 'DEBITI');